### ISSUE TITLE
ProcessMessagesAsync issue

### ISSUE THREAD

**Issue by MithrilMan** [davidfowl/DocsStaging#12]
I apprecciate the effort to explain how to use properly the pipelines.
There aren't much information on the wild about this, some of them are even discordant but what I wanted to point out now is that maybe the snippets should have an indeep coverage.

I saw the other open issue (#10) asking for full examples, I'm not in that position because snippets to me are fine (of course runnable code is better) but `ProcessMessagesAsync` seems to be a bit confusing or not working

here
`
// Process all messages from the buffer, modifying the input buffer on each iteration
while (TryParseMessage(ref buffer, out Message message))
`
you mention that input buffe gets modified every iteration, but don't say how.
trying to run this code causes an infinite loop because of course it won't exit from the `while` above.
In my effort to play with this.
I tried to slice the buffer in my TryParseMessage but I'm not sure this is the best way

`buffer = buffer.Slice(ms.Position);` 

(in my test i converted buffer to stream to use a method that needed a stream and then just used the stream position to advance, I know it's suboptimal but before moving to span, etc... I want to do basic tests

having said that, what's the reccomended approach? maybe passing to TryParseMessage the index of successfully parsed messages during its `while`?

In any case tha example should be improved :)
thanks

**Comment by davidfowl** [comment]
Hey @MithrilMan did you give this feedback since the docs have been migrated to https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines? 

That would be great! Even better would be a PR 👍🏾

**Comment by davidfowl** [comment]
To answer your specific question I'd need to see how you were parsing the buffer. If you use the SequenceReader then that would give you the position to advance to afterwards. If you convert to the stream (I wouldn't recommend that as it's inefficient) then you can use the position like you have in your example. If you have a length prefixed buffer then you can slice that length without any more work.

The answer is really, it depends.

**Comment by MithrilMan** [comment]
Ah damn I really can't remember the context of this answer, I guess I was looking into these datails after I found your BedrockFramework and started to get my hands dirty on the subject before using it (I created some issues on BedrockFramework too after few days)

Anyway I solved all problems and implemented a network protocol on your framework ( https://github.com/MithrilMan/MithrilShards/blob/5d947f85203f4b50346be2c5b84bedabc0ca21de/src/MithrilShards.Network.Bedrock/NetworkMessageProtocol.cs#L50-L94 )
